import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import type { AppScaffoldOptions, AppScaffoldResult } from '../types/index.js';
import { commandExists, runShell } from './shell.js';

export function scaffoldAppRepository(options: AppScaffoldOptions): AppScaffoldResult {
  const appName = normalizeName(options.appName || 'my-app');
  const appRepoPath = path.resolve(options.appRepoPath);
  const worktreesRootPath = path.resolve(options.worktreesRootPath);
  const overwrite = Boolean(options.overwrite);

  mkdirSync(appRepoPath, { recursive: true });
  mkdirSync(worktreesRootPath, { recursive: true });

  const createdFiles: string[] = [];
  const skippedExistingFiles: string[] = [];

  const initializedGit = ensureLocalGitRepo(appRepoPath);

  const files =
    options.mode === 'recommended'
      ? buildRecommendedTemplate(appName, worktreesRootPath)
      : buildCustomTemplate(appName, worktreesRootPath, options.customStackNotes);

  for (const [relative, content] of Object.entries(files)) {
    const fullPath = path.join(appRepoPath, relative);
    mkdirSync(path.dirname(fullPath), { recursive: true });
    if (existsSync(fullPath) && !overwrite) {
      skippedExistingFiles.push(fullPath);
      continue;
    }
    writeFileSync(fullPath, content, 'utf8');
    createdFiles.push(fullPath);
  }

  return {
    appName,
    mode: options.mode,
    appRepoPath,
    worktreesRootPath,
    initializedGit,
    createdFiles,
    skippedExistingFiles,
  };
}

function ensureLocalGitRepo(appRepoPath: string): boolean {
  if (!commandExists('git', appRepoPath)) {
    throw new Error('git is required but not available in PATH.');
  }
  const check = runShell('git', ['rev-parse', '--is-inside-work-tree'], appRepoPath, true);
  if (check.status === 0) return false;

  const initMain = runShell('git', ['init', '-b', 'main'], appRepoPath, true);
  if (initMain.status !== 0) {
    runShell('git', ['init'], appRepoPath);
    runShell('git', ['checkout', '-B', 'main'], appRepoPath, true);
  }
  return true;
}

function buildRecommendedTemplate(appName: string, worktreesRootPath: string): Record<string, string> {
  return {
    '.gitignore': [
      'node_modules/',
      '.next/',
      'dist/',
      '.env*',
      '.DS_Store',
      '',
    ].join('\n'),
    'README.md': [
      `# ${appName}`,
      '',
      'App scaffold generated by SpecToShip (recommended stack mode).',
      '',
      '## Stack',
      '- Next.js',
      '- TypeScript',
      '- Supabase-ready structure',
      '',
    '## Daily recipes',
    '- `just dev`',
    '- `just change-worktree <change-id> [provider]`',
    '- `just agent-verify`',
      '',
    ].join('\n'),
    'package.json': JSON.stringify(
      {
        name: appName,
        version: '0.1.0',
        private: true,
        scripts: {
          dev: 'next dev',
          build: 'next build',
          start: 'next start',
          lint: 'node -e "console.log(\'lint placeholder: configure eslint\')"',
          test: 'node -e "console.log(\'test placeholder: configure tests\')"',
          typecheck: 'tsc --noEmit',
          verify: 'npm run typecheck && npm run build',
        },
        dependencies: {
          next: '^15.0.0',
          react: '^18.3.0',
          'react-dom': '^18.3.0',
        },
        devDependencies: {
          '@types/node': '^22.10.0',
          '@types/react': '^18.3.12',
          '@types/react-dom': '^18.3.1',
          typescript: '^5.7.0',
        },
      },
      null,
      2,
    ) + '\n',
    'tsconfig.json': JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2022',
          lib: ['dom', 'dom.iterable', 'esnext'],
          allowJs: false,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          esModuleInterop: true,
          module: 'esnext',
          moduleResolution: 'bundler',
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: 'preserve',
          incremental: true,
        },
        include: ['next-env.d.ts', '**/*.ts', '**/*.tsx'],
        exclude: ['node_modules'],
      },
      null,
      2,
    ) + '\n',
    'next.config.mjs': 'const nextConfig = {};\n\nexport default nextConfig;\n',
    'next-env.d.ts': "/// <reference types='next' />\n/// <reference types='next/image-types/global' />\n",
    'app/layout.tsx': [
      "import type { ReactNode } from 'react';",
      '',
      'export default function RootLayout({ children }: { children: ReactNode }) {',
      '  return (',
      "    <html lang='en'>",
      '      <body>{children}</body>',
      '    </html>',
      '  );',
      '}',
      '',
    ].join('\n'),
    'app/page.tsx': [
      `export default function Home() {`,
      '  return (',
      "    <main style={{ padding: 24, fontFamily: 'sans-serif' }}>",
      `      <h1>${appName}</h1>`,
      "      <p>Scaffold created by SpecToShip recommended template.</p>",
      '    </main>',
      '  );',
      '}',
      '',
    ].join('\n'),
    'supabase/README.md': [
      '# Supabase (Local Runtime Placeholder)',
      '',
      'Initialize and configure local Supabase runtime for this app as needed.',
      '',
    ].join('\n'),
    'config/workspace.paths.json': JSON.stringify(
      {
        project_dir_name: appName,
        workdir_dir_name: `${appName}-workdir`,
        worktrees_root: worktreesRootPath,
      },
      null,
      2,
    ) + '\n',
    'scripts/create-change-worktree.sh': createChangeWorktreeScript(),
    'justfile': createAppJustfile(),
    'openspec/changes/README.md': '# Open changes for this app\n',
    'openspec/specs/README.md': '# Stable specs for this app\n',
  };
}

function buildCustomTemplate(appName: string, worktreesRootPath: string, notes?: string): Record<string, string> {
  return {
    '.gitignore': ['node_modules/', 'dist/', '.env*', '.DS_Store', ''].join('\n'),
    'README.md': [
      `# ${appName}`,
      '',
      'Custom app scaffold generated by SpecToShip.',
      '',
      'This mode lets you bring your own stack while preserving SpecToShip execution contracts.',
      notes ? '' : '',
      notes ? `Custom stack notes: ${notes}` : '',
      '',
    ]
      .filter(Boolean)
      .join('\n'),
    'package.json': JSON.stringify(
      {
        name: appName,
        version: '0.1.0',
        private: true,
        scripts: {
          lint: 'node -e "console.log(\'configure lint for your stack\')"',
          test: 'node -e "console.log(\'configure tests for your stack\')"',
          build: 'node -e "console.log(\'configure build for your stack\')"',
          verify: 'npm run lint && npm run test && npm run build',
        },
      },
      null,
      2,
    ) + '\n',
    'config/workspace.paths.json': JSON.stringify(
      {
        project_dir_name: appName,
        workdir_dir_name: `${appName}-workdir`,
        worktrees_root: worktreesRootPath,
      },
      null,
      2,
    ) + '\n',
    'scripts/create-change-worktree.sh': createChangeWorktreeScript(),
    'justfile': createAppJustfile(),
    'openspec/changes/README.md': '# Open changes for this app\n',
    'openspec/specs/README.md': '# Stable specs for this app\n',
  };
}

function createAppJustfile(): string {
  return [
    'set shell := ["bash", "-eu", "-o", "pipefail", "-c"]',
    '',
    'default:',
    '  @just --list',
    '',
    'change-worktree change_id provider="codex":',
    '  bash scripts/create-change-worktree.sh {{change_id}} {{provider}}',
    '',
    'agent-verify:',
    '  npm run verify',
    '',
    'dev:',
    '  npm run dev',
    '',
  ].join('\n');
}

function createChangeWorktreeScript(): string {
  return [
    '#!/usr/bin/env bash',
    'set -euo pipefail',
    '',
    'change_id="${1:-}"',
    'provider="${2:-codex}"',
    'provider="$(echo "$provider" | tr "[:upper:]" "[:lower:]" | sed -E "s/[^a-z0-9]+/-/g; s/^-+|-+$//g")"',
    'if [[ -z "$change_id" ]]; then',
    '  echo "Usage: bash scripts/create-change-worktree.sh <change-id> [provider]"',
    '  exit 1',
    'fi',
    'if [[ -z "$provider" ]]; then',
    '  provider="custom"',
    'fi',
    '',
    'repo_root="$(git rev-parse --show-toplevel)"',
    'branch="s2s-${provider}/${change_id}"',
    '',
    'cfg_path="$repo_root/config/workspace.paths.json"',
    'worktrees_root=""',
    'if [[ -f "$cfg_path" ]]; then',
    '  worktrees_root="$(node -e "const fs=require(\'fs\');const p=JSON.parse(fs.readFileSync(process.argv[1],\'utf8\'));process.stdout.write(String(p.worktrees_root||\'\'));" "$cfg_path")"',
    'fi',
    'if [[ -z "$worktrees_root" ]]; then',
    '  repo_name="$(basename "$repo_root")"',
    '  worktrees_root="$(cd "$repo_root/.." && pwd)/${repo_name}-worktrees"',
    'fi',
    '',
    'mkdir -p "$worktrees_root"',
    'worktree_path="$worktrees_root/$change_id"',
    '',
    'if ! git show-ref --verify --quiet "refs/heads/$branch"; then',
    '  git branch "$branch" >/dev/null',
    'fi',
    '',
    'if [[ -d "$worktree_path/.git" || -f "$worktree_path/.git" ]]; then',
    '  echo "path: $worktree_path"',
    '  exit 0',
    'fi',
    '',
    'git worktree add "$worktree_path" "$branch" >/dev/null',
    'echo "path: $worktree_path"',
    '',
  ].join('\n');
}

function normalizeName(value: string): string {
  const normalized = String(value || '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
  return normalized || 'my-app';
}
