import type { UserProjectGovernanceBundle, UserProjectGovernanceRenderContext } from './contracts.js';

export function renderUserProjectGovernance(
  context: UserProjectGovernanceRenderContext,
): UserProjectGovernanceBundle {
  return {
    guardrails: {
      agents: renderProjectAgentsGuardrail(context),
      codex: renderProjectCodexGuardrail(context),
      claude: renderProjectClaudeGuardrail(context),
    },
    rootBlocks: {
      agents: renderRootAgentsBlock(context),
      codex: renderRootCodexBlock(context),
      claude: renderRootClaudeBlock(context),
    },
  };
}

export function renderProjectAgentsGuardrail(context: UserProjectGovernanceRenderContext): string {
  return [
    '# S2S Orchestration Contract',
    '',
    'At session start: read `.s2s/live.md`. If status is not "none" (e.g. gate_pending, submitted), immediately tell the user what was in progress and ask if they want to continue or start something new. If status is "none", wait for user input.',
    'After context compression: long sessions may have their history summarized. If you notice prior conversation context has been compressed or summarized, immediately re-read `.s2s/live.md` and `.s2s/guardrails/AGENTS.md` to re-orient before proceeding.',
    'When user expresses an idea or task: run `s2s request "<idea>"` and follow the output.',
    'If uncertain at any point: read `.s2s/live.md` — it always contains the next action.',
    'For command reference: run `s2s help <command>` or read `.s2s/protocol.md`.',
    '',
    '## Stage Execution Pattern',
    '',
    'For each artifact-producing stage (pm, research, design, engineering):',
    '1. Run `s2s stage <stage>` — read the full task output',
    '2. Generate the required artifact content in this conversation',
    '3. Write each artifact to the exact path specified in the task output',
    '4. Run `s2s stage <stage> --submit` — s2s validates quality and outputs the next step',
    '',
    'After `--submit`, follow the next step instruction:',
    '- Quality passes, no gate: proceed to the next stage in the route',
    '- Quality fails: fix the issues listed and re-submit',
    '- Review gate created: STOP immediately. Tell the user the gate ID and instruct them to run `s2s approve <gateId>` in their terminal to continue, or `s2s reject <gateId>` to send it back. Do NOT call these commands yourself.',
    '',
    '`engineering_exec` (chat-native):',
    '1. Run `s2s stage engineering_exec` — s2s picks the next ready slice, starts a run, and prints the slice context',
    '2. Implement the slice directly in this conversation (create the branch, write the code, run tests, open PR)',
    '3. Run `s2s stage engineering_exec --submit` — s2s records the run complete and outputs the next step',
    '',
    '## Rules (never violate)',
    '- Never invent an s2s command or flag — always check `.s2s/protocol.md` first',
    '- Never skip `s2s stage <stage> --submit` after writing an artifact',
    '- Never proceed to the next stage without reading the next-action from `--submit`',
    '- Never modify `.s2s/live.md` — s2s writes it; you only read it',
    '- Never read raw `.s2s/` internal state files (changes/, specs/, gates/, ledger.json) — use `s2s show` commands instead',
    '- If an s2s command fails: show the error to the user, run `s2s status` and `s2s show` to diagnose via the public command surface, then propose a concrete fix; never read internal state files to investigate',
    '- Never edit project files without first confirming an active s2s run in `.s2s/live.md` — if no active run is present, route the user request through `s2s request` first',
    '- Never call `s2s approve` or `s2s reject` — these are human-only commands; always stop and tell the user to run them in their terminal',
    '',
    `Project root: ${context.appRoot}`,
  ].join('\n');
}

export function renderProjectCodexGuardrail(context: UserProjectGovernanceRenderContext): string {
  return [
    '# S2S Codex Adapter',
    '',
    'This file is the Codex-specific adapter for this s2s-managed project.',
    '',
    'At session start: read `.s2s/live.md`. If status is not "none" (e.g. gate_pending, submitted), immediately tell the user what was in progress and ask if they want to continue or start something new. If status is "none", wait for user input.',
    'After context compression: long sessions may have their history summarized. If you notice prior conversation context has been compressed or summarized, immediately re-read `.s2s/live.md` and `.s2s/guardrails/CODEX.md` to re-orient before proceeding.',
    'When user expresses an idea or task: run `s2s request "<idea>"` and follow the output.',
    'If uncertain at any point: read `.s2s/live.md` — it always contains the next action.',
    'For command reference: run `s2s help <command>` or read `.s2s/protocol.md`.',
    '',
    '## Stage Execution Pattern (Codex)',
    '',
    'For each artifact-producing stage (pm, research, design, engineering):',
    '1. Run `s2s stage <stage>` — read the full task output',
    '2. Generate the required artifact content in this conversation',
    '3. Write each artifact to the exact path specified in the task output',
    '4. Run `s2s stage <stage> --submit` — s2s validates quality and outputs the next step',
    '',
    'After `--submit`, follow the next step instruction:',
    '- Quality passes, no gate: proceed to the next stage in the route',
    '- Quality fails: fix the issues listed and re-submit',
    '- Review gate created: STOP immediately. Tell the user the gate ID and instruct them to run `s2s approve <gateId>` in their terminal to continue, or `s2s reject <gateId>` to send it back. Do NOT call these commands yourself.',
    '',
    '`engineering_exec` (chat-native):',
    '1. Run `s2s stage engineering_exec` — s2s picks the next ready slice, starts a run, and prints the slice context',
    '2. Implement the slice directly in this conversation (create the branch, write the code, run tests, open PR)',
    '3. Run `s2s stage engineering_exec --submit` — s2s records the run complete and outputs the next step',
    '',
    '## Rules (never violate)',
    '- Never invent an s2s command or flag — always check `.s2s/protocol.md` first',
    '- Never skip `s2s stage <stage> --submit` after writing an artifact',
    '- Never proceed to the next stage without reading the next-action from `--submit`',
    '- Never modify `.s2s/live.md` — s2s writes it; you only read it',
    '- Never read raw `.s2s/` internal state files (changes/, specs/, gates/, ledger.json) — use `s2s show` commands instead',
    '- If an s2s command fails: show the error to the user, run `s2s status` and `s2s show` to diagnose via the public command surface, then propose a concrete fix; never read internal state files to investigate',
    '- Never edit project files without first confirming an active s2s run in `.s2s/live.md` — if no active run is present, route the user request through `s2s request` first',
    '- Never call `s2s approve` or `s2s reject` — these are human-only commands; always stop and tell the user to run them in their terminal',
    '',
    `Project root: ${context.appRoot}`,
  ].join('\n');
}

export function renderProjectClaudeGuardrail(context: UserProjectGovernanceRenderContext): string {
  return [
    '# S2S Claude Adapter',
    '',
    'This file is the Claude-specific adapter for this s2s-managed project.',
    '',
    'At session start: read `.s2s/live.md`. If status is not "none" (e.g. gate_pending, submitted), immediately tell the user what was in progress and ask if they want to continue or start something new. If status is "none", wait for user input.',
    'After context compression: Claude Code may compress long conversation history mid-session. If you see a system message indicating the session was summarized or continued from a prior conversation, immediately re-read `.s2s/live.md` and `.s2s/guardrails/CLAUDE.md` to re-orient before proceeding. Do not continue implementing changes without first re-establishing the current s2s state.',
    'When user expresses an idea or task: run `s2s request "<idea>"` and follow the output.',
    'If uncertain at any point: read `.s2s/live.md` — it always contains the next action.',
    'For command reference: run `s2s help <command>` or read `.s2s/protocol.md`.',
    '',
    '## Stage Execution Pattern (Claude)',
    '',
    'For each artifact-producing stage (pm, research, design, engineering):',
    '1. Run `s2s stage <stage>` — read the full task output',
    '2. Generate the required artifact content in this conversation',
    '3. Write each artifact to the exact path specified in the task output',
    '4. Run `s2s stage <stage> --submit` — s2s validates quality and outputs the next step',
    '',
    'After `--submit`, follow the next step instruction:',
    '- Quality passes, no gate: proceed to the next stage in the route',
    '- Quality fails: fix the issues listed and re-submit',
    '- Review gate created: STOP immediately. Tell the user the gate ID and instruct them to run `s2s approve <gateId>` in their terminal to continue, or `s2s reject <gateId>` to send it back. Do NOT call these commands yourself.',
    '',
    '`engineering_exec` (chat-native):',
    '1. Run `s2s stage engineering_exec` — s2s picks the next ready slice, starts a run, and prints the slice context',
    '2. Implement the slice directly in this conversation (create the branch, write the code, run tests, open PR)',
    '3. Run `s2s stage engineering_exec --submit` — s2s records the run complete and outputs the next step',
    '',
    '## Rules (never violate)',
    '- Never invent an s2s command or flag — always check `.s2s/protocol.md` first',
    '- Never skip `s2s stage <stage> --submit` after writing an artifact',
    '- Never proceed to the next stage without reading the next-action from `--submit`',
    '- Never modify `.s2s/live.md` — s2s writes it; you only read it',
    '- Never read raw `.s2s/` internal state files (changes/, specs/, gates/, ledger.json) — use `s2s show` commands instead',
    '- If an s2s command fails: show the error to the user, run `s2s status` and `s2s show` to diagnose via the public command surface, then propose a concrete fix; never read internal state files to investigate',
    '- Never edit project files without first confirming an active s2s run in `.s2s/live.md` — if no active run is present, route the user request through `s2s request` first',
    '- Never call `s2s approve` or `s2s reject` — these are human-only commands; always stop and tell the user to run them in their terminal',
    '',
    `Project root: ${context.appRoot}`,
  ].join('\n');
}

export function renderRootAgentsBlock(context: UserProjectGovernanceRenderContext): string {
  return [
    '# S2S Workspace Shim',
    '',
    'This repository is configured with s2s.',
    'This root block is a compatibility shim for chat clients.',
    '',
    'Authoritative project governance lives in:',
    '- `.s2s/guardrails/AGENTS.md`',
    '- `.s2s/config/runtime.json`',
    '',
    'If root instructions conflict with `.s2s/guardrails/*`, `.s2s/guardrails/*` takes precedence.',
    'Canonical behavior lives in `.s2s/guardrails/*`.',
    'When already running inside an s2s-managed stage execution, do not run `s2s` again.',
    '',
    `Project root: ${context.appRoot}`,
  ].join('\n');
}

export function renderRootCodexBlock(context: UserProjectGovernanceRenderContext): string {
  return [
    '# S2S Codex Root Shim',
    '',
    'This project is governed by s2s.',
    'This root block is a compatibility shim for Codex.',
    '',
    'Authoritative context before execution:',
    '- `.s2s/guardrails/AGENTS.md`',
    '- `.s2s/guardrails/CODEX.md`',
    '- `.s2s/config/runtime.json`',
    '',
    'Conflict rule: if any root instruction contradicts `.s2s/guardrails/*`, follow `.s2s/guardrails/*`.',
    'Canonical behavior lives in `.s2s/guardrails/*`.',
    'If you are already running inside an s2s-managed stage execution, do not run `s2s` again.',
    '',
    `Project root: ${context.appRoot}`,
  ].join('\n');
}

export function renderRootClaudeBlock(context: UserProjectGovernanceRenderContext): string {
  return [
    '# S2S Claude Root Shim',
    '',
    'This project is governed by s2s.',
    'This root block is a compatibility shim for Claude.',
    '',
    'Authoritative context before execution:',
    '- `.s2s/guardrails/AGENTS.md`',
    '- `.s2s/guardrails/CLAUDE.md`',
    '- `.s2s/config/runtime.json`',
    '',
    'Conflict rule: if any root instruction contradicts `.s2s/guardrails/*`, follow `.s2s/guardrails/*`.',
    'Canonical behavior lives in `.s2s/guardrails/*`.',
    'If you are already running inside an s2s-managed stage execution, do not run `s2s` again.',
    '',
    `Project root: ${context.appRoot}`,
  ].join('\n');
}
