// SpecToShip — Public API

export { initProject, runStage, runAllStages, getProjectStatus } from './conductor/pipeline.js';
export { runIteration } from './conductor/iterate.js';
export {
  buildEngineeringExecutionHandoff,
  buildExecutionTraceabilityRecord,
  buildSliceContextDocument,
  renderExecutionTraceabilityDocument,
  runEngineeringExecution,
} from './runtime/engineering-exec.js';
export {
  loadRuntimeConfig,
  saveRuntimeConfig,
  getRuntimeConfigPath,
  bootstrapWorkspace,
  loadExecutionTemplates,
  resolveExecutionTemplate,
} from './runtime/config.js';
export { resolveWorkspacePaths, ensureWorkspaceLayout } from './runtime/workspace-manager.js';
export { ensureGitRepository, ensureOrInitGitRepository, hasGitRemote } from './runtime/github-operator.js';
export { runEngineeringWorker } from './runtime/engineering-worker.js';
export { scaffoldAppRepository } from './runtime/app-scaffold.js';
export {
  assessLightweightPrerequisites,
  assessRuntimeReadiness,
  createExpectedProjectRuntimeConfig,
  ensureRuntimeReady,
  checkCoreTools,
  resolveEnabledReadinessFeatures,
  summarizeReadinessChecks,
} from './runtime/readiness.js';
export { assessInitPrerequisites } from './runtime/init-prerequisites.js';
export { materializeOpenSpecChange } from './runtime/openspec-bridge.js';
export { executeOpenSpecTasks } from './runtime/task-executor.js';
export {
  buildWorktreeSessionId,
  cloneWorktreeSession,
  createWorktreeProvider,
  deriveWorktreePathSegment,
  deriveWorktreeSessionPurpose,
  expandHomePath,
  normalizeWorktreeProviderConfig,
  providerSupportsCapability,
  resolveLocalS2SControlRoot,
  resolveLocalS2SRepoWorktreesRoot,
  resolveLocalS2SRuntimeRoot,
  resolveLocalS2SWorktreesRoot,
  resolveWorktreeRuntimePaths,
  resolveWorktreeProviderStateRoot,
  resolveWorktreeSessionPath,
} from './runtime/worktree-provider.js';
export {
  createWorktrunkWorktreeProvider,
  parseWorktrunkListOutput,
} from './runtime/worktree-provider-worktrunk.js';
export { createNativeWorktreeProvider } from './runtime/worktree-provider-native.js';
export { classifyIntent } from './orchestrator/intent-classifier.js';
export { resolveContext } from './orchestrator/context-resolver.js';
export { buildFlowDecision, planFlow } from './orchestrator/flow-planner.js';
export { buildRouteDecision } from './orchestrator/stage-router.js';
export {
  advanceStageOwnership,
  advanceStageOwnershipFromDecision,
  buildOrchestrationDecisionRecord,
  decideOrchestration,
  decideRoute,
  initializeChange,
  initializeChangeFromDecision,
  initializeSpec,
  initializeSpecFromDecision,
  recordOrchestrationDecision,
} from './orchestration/router.js';
export { resolveRuntimePolicy, requiresApprovalForStage } from './orchestration/policy.js';
export { saveFigmaSnapshot, loadFigmaSnapshot, diffSnapshot } from './figma/sync.js';
export { loadFigmaConfig, isFigmaConfigured } from './figma/config.js';
export { runQualityChecks } from './quality/checks.js';
export { createProvider } from './providers/interface.js';
export { loadPricingConfig, resolvePricingModel } from './costs/pricing.js';
export {
  collectPersistedDesignArtifacts,
  DESIGN_OUTPUT_ARTIFACTS,
  PRIMARY_DESIGN_DEFINITION_LABEL,
  collectDesignRequestSignals,
  hasPersistedDesignDefinition,
  isDesignOutputArtifactLabel,
  isPrimaryDesignDefinitionLabel,
  resolveDesignContextHandoff,
} from './agents/design.js';
export {
  collectSupportingArtifactsForSliceDerivation,
  createSliceDerivationInput,
  createSliceDerivationPlan,
  deriveAndPersistSlices,
  derivePersistedSliceId,
  deriveSlicePlan,
  deriveSliceDrafts,
  deriveSliceKeyFromTaskId,
  parseSliceDerivationBacklog,
  parseSliceDerivationInput,
  parseSliceDerivationTechSpecSections,
  persistSlicePlan,
} from './ledger/derive-slices.js';
export {
  approveGate,
  cancelGate,
  changeExists,
  createChange,
  createExecutionRun,
  createRefinementSpecVersion,
  createGate,
  createWorkGate,
  createLedger,
  createRun,
  createSlice,
  createSpec,
  completeExecutionRun,
  deleteChange,
  deleteGate,
  deleteLedger,
  deleteRun,
  deleteSlice,
  deleteSpec,
  derivePersistedRunId,
  deriveLedger,
  getChange,
  getActiveChange,
  getActiveChangeId,
  getActiveSpec,
  getActiveSpecId,
  getGate,
  getLedger,
  getRun,
  getSlice,
  getSpec,
  gateExists,
  hasMaterializedSpecHistory,
  ledgerExists,
  listExecutableSlices,
  listBlockedChangeIds,
  listBlockedChanges,
  listOpenChanges,
  listOpenRuns,
  listOpenSlices,
  listOpenSpecs,
  listChanges,
  listAllowedStatusTransitions,
  listGates,
  listPendingGateIds,
  listPendingGates,
  listRunIdsByStatus,
  listRunsByStatus,
  listRuns,
  listSliceIdsByStatus,
  listSlicesByStatus,
  listSlices,
  listSpecs,
  markExecutionRunVerifying,
  rejectGate,
  refreshLedger,
  requireNextExecutableSlice,
  requireChange,
  requireActiveChange,
  requireActiveSpec,
  requireGate,
  requireLedger,
  requireRun,
  requireSlice,
  requireSpec,
  runExists,
  saveChange,
  saveGate,
  saveLedger,
  saveRun,
  saveSlice,
  saveSpec,
  resolveGate,
  resolveExecutableSliceSelection,
  selectNextExecutableSlice,
  sliceExists,
  startExecutionRun,
  specExists,
  updateChange,
  updateGate,
  updateLedger,
  updateRun,
  updateSlice,
  updateSpec,
  assertValidStatusTransition,
  isValidStatusTransition,
  workEntityStatusTransitions,
} from './ledger/index.js';
export {
  enforceBudgetBeforeRequest,
  recordUsageEventFromCompletion,
  loadUsageSummary,
  readUsageEvents,
  listProjectsWithUsage,
  resolveCostControl,
} from './costs/tracker.js';
export {
  buildArtifactTreeFromLabels,
  buildArtifactTreeFromPaths,
  renderArtifactTree,
  renderBlocks,
  renderDoctorCheckMatrix,
  renderNextActionsBlock,
  renderPhaseProgressBlock,
  renderStatusBlock,
  renderSummaryBlock,
  renderWarningsBlock,
} from './output/renderers.js';
export { detectUITargetOptions, pickDefaultUITarget, templateFromUI } from './runtime/ui-targets.js';
export {
  CLISharedFlagNames,
  ORCHESTRATION_DECISION_RECORD_VERSION,
  SLICE_DERIVATION_CONTRACT_VERSION,
  SliceDerivationArtifactPaths,
  SliceDerivationBacklogColumns,
  SliceDerivationTechSpecHeadings,
} from './types/index.js';

// Re-export types
export type {
  ProjectIdea,
  PipelineStage,
  PipelineState,
  AgentRole,
  AgentResult,
  LLMProvider,
  LLMProviderConfig,
  QualityCheckResult,
  QualityReport,
  FigmaConfig,
  FigmaSnapshot,
  SnapshotDiff,
  StageResult,
  WorkIntent,
  IntentClassification,
  WorkEntityStatus,
  DesignContextHandoff,
  FlowDecision,
  FlowExpansionDecision,
  OrchestrationDecisionRecord,
  OrchestrationDecisionRecordVersion,
  WorkArtifactReference,
  WorkScopeDefinition,
  SliceDerivationContractVersion,
  SliceDerivationArtifactPath,
  SliceDerivationTechSpecHeading,
  SliceDerivationBacklogColumn,
  SliceDerivationTechSpecSections,
  SliceDerivationBacklogItem,
  SliceDerivationInput,
  SliceDerivationDraft,
  SliceDerivationTaskSubsetItem,
  SliceDerivationPlanSlice,
  SliceDerivationPlan,
  CreateRefinementSpecVersionOptions,
  CreateExecutionRunOptions,
  CreateWorkGateOptions,
  UpdateExecutionRunOptions,
  ResolveWorkGateOptions,
  PersistSlicePlanOptions,
  PersistSlicePlanResult,
  RefinementSpecVersionResult,
  WorkChangeRequest,
  WorkChange,
  ChangeInitializationResult,
  SpecInitializationResult,
  StageOwnershipUpdateResult,
  WorkSpec,
  WorkSlice,
  WorkRunEvidence,
  WorkRun,
  ExecutionTraceabilityRecord,
  WorkRunLifecycleResult,
  WorkGateLifecycleResult,
  WorkGateDecision,
  WorkGate,
  WorkLedger,
  ExecutableSliceCandidate,
  ExecutableSliceSelection,
  ExecutableSliceSelectionOptions,
  WorkChangeStatus,
  ContextResolution,
  ContextResolutionFlags,
  WorkSpecStatus,
  WorkSliceStatus,
  WorkRunStatus,
  WorkGateStatus,
  WorkGateType,
  WorkEntityKind,
  WorkEntityRecordMap,
  WorkEntityRecord,
  WorkPriority,
  WorkSliceSize,
  WorkArtifactKind,
  WorktreeProviderKind,
  WorktreeProviderCapability,
  WorktreeSessionState,
  WorktreeSessionPurpose,
  WorktreePullRequestState,
  WorktreeValidationAction,
  ReadinessScope,
  ReadinessRequirement,
  ReadinessStatus,
  ReadinessFeature,
  CLISharedFlagName,
  CLISharedFlags,
  ReadinessCheck,
  ReadinessSummaryBucket,
  ReadinessFeatureSummary,
  RuntimeReadinessReport,
  InitReadinessChecklistItem,
  InitPrerequisiteReport,
  LightweightPrerequisiteCheckOptions,
  LightweightPrerequisiteCommand,
  LightweightPrerequisiteReport,
  OutputRendererArtifactNode,
  OutputRendererMetadataItem,
  OutputRendererPhaseStep,
  OutputRendererState,
  OutputRendererStatusItem,
  WorktreeRuntimePaths,
  WorktreeProviderConfig,
  WorktreeProviderAvailability,
  WorktreeSessionPullRequestRef,
  WorktreeSession,
  WorktreeSessionRequest,
  WorktreeSessionQuery,
  WorktreeSessionRemoval,
  WorktreeSessionValidation,
  WorktreePullRequestWorkspaceRequest,
  WorktreeProvider,
  IterationResult,
  ProjectStatus,
  RouteStageAction,
  RouteDecision,
  RouteStageDecision,
  RouterIntent,
  RuntimePolicy,
  RuntimeConfig,
  ExecutionCommandTemplate,
  EngineeringExecOptions,
  EngineeringExecutionHandoff,
  EngineeringExecutionTaskHandoff,
  EngineeringExecResult,
  RuntimeWorkspacePaths,
  WorkspaceBootstrapOptions,
  WorkspaceBootstrapResult,
  AppStackMode,
  AppScaffoldOptions,
  AppScaffoldResult,
} from './types/index.js';
